version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(asctime)s %(levelname)s %(name)s | %(message)s'
handlers:
  file:
    class: logging.FileHandler
    filename: uvicorn.log
    formatter: default
  console:
    class: logging.StreamHandler
    formatter: default
loggers:
  uvicorn:
    level: INFO
    handlers:
      - file
      - console
    propagate: True
  uvicorn.error:
    level: INFO
    handlers:
      - file
      - console
    propagate: True
  uvicorn.access:
    level: INFO
    handlers:
      - file
      - console
    propagate: True
